kind: pipeline
name: default

steps:
    - name: provision
      build:
          image: local/${DRONE_REPO_NAME}
          context: .
          dockerfile: Dockerfile.ci
      when:
          event:
              - pull_request
    - name: install
      image: local/${DRONE_REPO_NAME}
      commands:
          - whoami
          - pwd
          - ls -la
      when:
          event:
              - pull_request
